## plot annotations summaried by Homer annotateStats
 
library(ggpubr)
library(plyr)
library(magrittr)

args = commandArgs(trailingOnly=TRUE)

inputfile <- args[1] ## table generated by Homer annotateStats option
wd <- args[2]
plotd <- args[3]
target <- args[4]

setwd(wd)
total_table <- read.delim(inputfile, header=T, sep="\t")
total_table <- as.data.frame(total_table[1:12,])
total_count_table <- type.convert(total_table[,2:ncol(total_table)])

rownames(total_count_table) <- total_table[,"Annotation"]
total_count_table <- total_count_table[c("Promoter", "5UTR", "Exon", "3UTR", "TTS", "Intron", "miRNA", "ncRNA", "snoRNA", "snRNA", "pseudo", "Intergenic"),] %>%
        mutate(Feature=c("Promoter", "5'UTR", "CDS", "3'UTR", "TES", "Intron", "miRNA", "ncRNA", "snoRNA", "snRNA", "Pseudogene", "Intergenic")) %>%
	mutate(Percentage=round(Number.of.peaks*100/sum(Number.of.peaks)))

labs <- paste(total_count_table$Percentage,"%",sep="")
p <- ggbarplot(total_count_table, x="Feature", y="Percentage", fill="Feature", color="white", palette="ucscgb",
	xlab=FALSE, main=inputfile) %>%
	ggpar(legend="none", x.text.angle=45, ylim=c(0,100), yticks.by=10) + 
	grids(axis="y", linetype = "dashed")

ggexport(p, filename=file.path(plotd, "peak_annotation_barchart_complete.pdf"))

write.table(total_count_table, file.path(plotd, paste(target,"_peak_annotation_table_for_barchart_complete.tab", sep="")), col.names=NA, sep="\t", quote=F)


ann_table <- total_table[total_table$Annotation %in% c("Promoter", "5UTR", "Exon", "3UTR", "TTS"),]
count_table <- type.convert(ann_table[,2:ncol(ann_table)])
rownames(count_table) <- ann_table[,"Annotation"]
count_table <- count_table[c("Promoter", "5UTR", "Exon", "3UTR", "TTS"),] %>%
        mutate(Feature=c("Promoter", "5'UTR", "CDS", "3'UTR", "TES")) %>%
	mutate(Percentage=round(Number.of.peaks*100/sum(Number.of.peaks)))
	
labs <- paste(count_table$Percentage,"%",sep="")
p <- ggpie(count_table, x="Percentage", label=labs, lab.pos="out", fill="Feature", color="white", palette="ucscgb")

ggexport(p, filename=file.path(plotd, "peak_annotation_piechart.pdf")) 

write.table(count_table, file.path(plotd, paste(target,"_peak_annotation_table_for_piechart.tab", sep="")), col.names=NA, sep="\t", quote=F)


